### ISSUE TITLE
Plugin not finding nim compiler in $PATH

### ISSUE THREAD

**Issue by damienstanton** [zah/nim.vim#35]
When opening a test .nim file using Vim or GVim 7.4 on Ubuntu 14.10:

``` vim
"test.nim" [New File]
Error detected while processing /home/.vim/bundle/nimrod.vim/autoload/nim.vim:
line 9:
the Nim compiler must be in your system's PATH
```

The nim compiler is definitely in the PATH (I can call it without issues), and this error even appears when I set vim to silent. The issue doesn't occur on a similar installation on OS X.

Also, I should note the syntax and indentation _is_ working as expected, there is just a spurious error when launching.

**Comment by tony-austin** [comment]
update your shell profile, typically:   ~/.profile or ~/.bash_profile
as recommeded Dennis Felsing:
http://www.howistart.org/posts/nim/1
