### ISSUE TITLE
Does this plugin require vim compiled with the python flag?

### ISSUE THREAD

**Issue by daveyarwood** [zah/nim.vim#55]
After installing the Nim compiler to my PATH and installing nim.vim, on opening a nim buffer I get this error:

```
Error detected while processing /Users/dave/.vim/bundle/nim.vim/autoload/nim.vim:
line   12:
E117: Unknown function: provider#python#Call
```

My vim was not compiled with the python flag. Do you think that's the cause, or is this something else?

**Comment by zah** [comment]
Yes, Python is currently required to simulate asynchronous operation in Vim when talking to the Nim compiler. I hope to remove this dependency in the future in favour of the built-in async sypport in Vim 8 and NeoVim.

**Comment by daveyarwood** [comment]
Sounds good!

**Comment by uninhm** [comment]
I'm getting this error on neovim, but there is no python flag to build...
