### ISSUE TITLE
there is an error about 'nimTerminateAll'

### ISSUE THREAD

**Issue by zer0-star** [zah/nim.vim#83]
i use neovim, and when i close file *.nim, an error occurs.
it won't affect something, but i want to make it go away.
what should i do?

**Comment by Electrux** [comment]
I am encountering this error too... it goes too fast to read as well. Neovim 0.2.2, using Vim-Plug.
Please help, thanks :)

**Comment by jonathanabennett** [comment]
I'm having the same error. The exact error is:

  Executing VimLeavePre Auto commands for "*"
  autocommand :py nimTerminateAll()

  Searching for "autoload/provider/python.vim" in 
  "/home/doulos05/.vim,/home/doulos05/.vim/plugged/vimwiki/,/home/doulos05/.vim/plugged/vim-plug/,/home/doulos05/.vim/plugged/taskwiki/,/home/doulos05/.vim/plugged/lightline.vim/,/home/doulos05/.vim/plugged/calendar-vim/,/home/doulos05/.vim/plugged/nim.vim/,/home/doulos05/.config/nvim,/etc/xdg/nvim,/home/doulos05/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/home/doulos05/.local/share/nvim/site/after,/etc/xdg/nvim/after,  
 /home/doulos05/.config/nvim/after,/home/doulos05/.vim/plugged/taskwiki/after,/home/doulos05/.vim/after"
  Searching for "/home/doulos05/.vim/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/vimwiki/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/vim-plug/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/taskwiki/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/lightline.vim/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/calendar-vim/autoload/provider/python.vim"
  Searching for "/home/doulos05/.vim/plugged/nim.vim/autoload/provider/python.vim"
  Searching for "/home/doulos05/.config/nvim/autoload/provider/python.vim"
  Searching for "/etc/xdg/nvim/autoload/provider/python.vim"
  Searching for "/home/doulos05/.local/share/nvim/site/autoload/provider/python.vim"
  Searching for "/usr/local/share/nvim/site/autoload/provider/python.vim"
  Searching for "/usr/share/nvim/site/autoload/provider/python.vim" 
  Searching for "/usr/share/nvim/runtime/autoload/provider/python.vim"
  chdir(/home/doulos05/coding/mountainhome)
  chdir(/usr/share/nvim/runtime/autoload/provider)
  chdir(/home/doulos05/coding/mountainhome)
  line 0: sourcing "/usr/share/nvim/runtime/autoload/provider/python.vim"
  finished sourcing /usr/share/nvim/runtime/autoload/provider/python.vim
  continuing in VimLeavePre Auto commands for "*"
                                               Error detected while processing function provider#python#Call:
line   18:
  Traceback (most recent call last):

    File "<string>", line 1, in <module>
  
  NameError: name 'nimTerminateAll' is not defined
  Writing ShaDa file "/home/doulos05/.local/share/nvim/shada/main.shada"

**Comment by sagax** [comment]
VIM - Vi IMproved 8.1
nim.vim - 7d1211c

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'nimTerminateAll' is not defined
```

**Comment by zer0-star** [comment]
It's not necessary to keep this issue opened any longer. I solved.
Thanks.
